### ISSUE TITLE
Repo for documentation Site

### ISSUE THREAD

**Issue by joezimjs** [uloga/modulr.css#1]
I can't find a repository for the documentation site. There are a lot of typos I'd be glad to help fix up, but it doesn't look like it's accessible to "outsiders". :)

**Comment by uloga** [comment]
Hi Joe, thanks for the interest. There is no docs repo yet,  I will create a docs repo  next week. Could you please email me the typos for now. wpnemesis@gmail.com  Thanks in advance! :)

**Comment by uloga** [comment]
I've created a docs folder in modulr.css repo. Tomorrow, I will commit the documentation files.

**Comment by uloga** [comment]
Docs are on github, anyone who wishes to help out and improve the docs can do so  by clicking on 
"Improve this Doc" link that can be found on the top right side of each documentation page @ https://decorator.io/modulr/  

I'm working on finishing the CLI and the rest of the framework, also creating some test examples before official release. Thanks ! :)
