### ISSUE TITLE
Fix English on website and README

### ISSUE THREAD

**Issue by sreisner** [uloga/modulr.css#2]
Your main blurb currently reads

> Modulr.css is fast and easy modular approach to building powerful web and mobile interfaces.

but it should read something like

> Modulr.css is _the_ fast and easy modular approach to building powerful web and mobile interfaces.

**Comment by uloga** [comment]
Yep, thanks for mentioning that. :+1:  :)

**Comment by uloga** [comment]
It was Modulr.css : A Fast and easy, but for some reason I've changed it without noticing the mistake, thanks ! :)
