### ISSUE TITLE
Class -rounded on Select does not work on WebKit Mac OS browser

### ISSUE THREAD

**Issue by mogholito** [uloga/modulr.css#4]
Hi,
I'm currently trying your CSS framework on one project for now and I noticed that using the class -rounded on a collapsed Select element, as in your form example or your tutorial example (https://decorator.io/modulr/docs/form), does not work in Chrome/Safari Mac browser (Chrome Windows render it properly).
I suggest you add the specific properties `-webkit-appearance: none;
-webkit-border-radius: 0px;` to remove radius properly. 
With my encouragement for your excellent work.

**Comment by uloga** [comment]
Hi mogholito,
Thanks for the interest. :)  Lately, I'm very busy with my startup but will soon push version 2.

Feel free to contribute your code. :) Click on link below. 

https://github.com/uloga/modulr.css/blob/master/css/modulr/core/modifier.css#L371
