### ISSUE TITLE
Problem with the colors

### ISSUE THREAD

**Issue by godambrosio** [uloga/modulr.css#6]
When I use the next tag for example

`<div class="navbar purple">`

The div take the default color of the navbar instead of purple.

May be add !important to the module colors ?

Thanks.

**Comment by uloga** [comment]
If you are using @import make sure that you @import colors at the end of the file.
Works for fine me as you can see in this example: 

http://codepen.io/decorator/full/yOKPyX

**Comment by uloga** [comment]
I've just created a pen at codepen which proves that this is not the issue:
Check out the link below:
http://codepen.io/decorator/pen/NbxrQN

**Comment by godambrosio** [comment]
Ok thanks a lot and sorry for the noise.

**Comment by uloga** [comment]
No problem bro, you're most welcome. :) 

Thanks for trying out Modulr.css 

Have a nice day.
